### PR TITLE
Upgrade to latest framework and dependencies

### PR DESCRIPTION
**Pull request by JovialJerboa**
- Clean up csproj files
- Remove unused framework in the plugin project
- Upgrade to .NET 6.0 (latest long term support version)
- Upgraded all dependencies

### CODE REVIEW

**Comment by JovialJerboa** [comment]
@wenyuansong thanks so much for your work on this project!

I was using it on a personal project and was receiving some NU1608 warnings as this package references some older versions of the SpecFlow packages.

I wanted to know when it might be upgraded, but thought it might better if I created a PR for you instead.

Let me know if you have any questions

**Review by wenyuansong — APPROVED** [review]
Hi Liam,

Thank you so much for contributing to this. 
Will merge the PR and publish a new NuGet version soon.  

Cheers,
Ryan

**Comment by wenyuansong** [comment]
Hi @JovialJerboa,  any reason why net461 was removed from targetNetworks?  I think it's to allow projects using .netframework can use the plugin.

**Comment by JovialJerboa** [comment]
Hey @wenyuansong, 

`netstandard2.0` is compatible with `.NET` / `.NET Core` `v2.0+` and `.NET Framework` `4.6.1+` so I don't think it was necessary to have it in the `Specflow.DSL.SpecFlowPlugin.csproj` ([docs](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0) for reference).

If you want to support earlier versions of `.NET` / `.NET Core` `v2.0+` and `.NET Framework`, depending on the specific APIs being used you could target an ealier version of `.NET Standard` or like you were doing before target the specific framework versions.

Also just FYI in terms of other changes that might not be obvious:
- The removal of `SpecRun.SpecFlow` and replacement with `xunit` is because the SpecFlow team have sunset the [SpecFlow+runner project](https://specflow.org/using-specflow/the-retirement-of-specflow-runner/)

Let me know if you have any other questions and thanks again for your work

**Comment by JovialJerboa** [comment]
Hey @wenyuansong 

Did my previous comment make sense? Do you have any questions?

When do you expect to be able to make a release? Is there anything I can do to support a new release with the changes?

Thanks!

**Comment by wenyuansong** [comment]
Hi Liam,

Thanks for your email.
Sorry for not replying earlier.
I was looking at specflow official plugin reference where both framework
4.6.2 and .net2.0 are recommended.
https://docs.specflow.org/projects/specflow/en/latest/Extend/Plugins.html

 I believe .net2.0 runtime is compatible with 4.6.2 runtime but when nudget
manager searches for compatible packages it will only match either
framework or dotnet. haven't got time to verify it yet. It would be great
if you can help with it. Otherwise i will spare some time on Sunday to
verify and release a new version.  Also looking at setting up github
actions to automate the release process.  Happy to add you as admin if you
would like to continuosly manage the repo and nudget package.

Cheers,
Ryan

**Comment by JovialJerboa** [comment]
@wenyuansong looks like there are edge case compatability issues between `net461` and `netstandard2.0` (CF: [Cross-platform targeting](https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting)).

image

It seems like it is worth having the `net461` target in there to make it available to developers using `net461` if they need the enhanced compatibility.

I'll make a new PR to add it back in now.

If you'd like to add me as an admin I'm happy to join you and push out a release. Is there anything I need to understand in terms of making a release?

**Comment by wenyuansong** [comment]
Hi Liam,

Thanks for sharing your findings.
I've sent you a collaborator invitation and will try to get github action
working to do release automatically - will send a PR once it's done.

Cheers,
Ryan

**Pull request merged**
